In [ ]:
import tensorflow as tf

x = tf.Variable(0.5, dtype=tf.float32)
print(x)
print(float(x))
print(x.numpy())
assert x.numpy() == float(x)
y = 0.7
print(float(y))

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.5>
0.5
0.5
0.7


In [11]:
a = [1, 2]; b = [3, 4]
c = list(zip(a, b))
for (p, q) in list(c):
    print(p, q)

1 3
2 4


In [ ]:
def fun(x):
    print("fun")
    print(x)
a = [1]
print(a)
del a

try: a 
except NameError:
    print('name error')
else:
    print('not name error')


[1]
name error


In [ ]:
import tensorflow as tf
import numpy as np

class recall():
  def __init__(self, **kwargs):
    self.n = None
    self.recall = None
    self.reset()

  def update(self, label, pred):    # (batch,)
    label = tf.cast(label, dtype=tf.float32)
    pred = tf.cast(pred, dtype=tf.float32)
    hit_positives = tf.math.reduce_sum(label * pred, axis=None)
    labeled_positives = tf.math.reduce_sum(label, axis=None)
    recall = hit_positives / (labeled_positives + 1e-9) #tf.keras.backend.epsilon())
    self.n += 1
    self.recall = self.recall * (self.n-1)/self.n + recall / self.n

  def result(self):
    return self.recall
  
  def reset(self):
    self.n = 0
    self.recall = tf.Variable(0.0, dtype=tf.float32)
  
recall_object = recall(min_seq_len=5)

class precision():
  def __init__(self, **kwargs):
    self.n = None
    self.precision = None
    self.reset()

  def update(self, label, pred):
    label = tf.cast(label, dtype=tf.float32)
    pred = tf.cast(pred, dtype=tf.float32)
    hit_positives = tf.math.reduce_sum(label * pred, axis=None)
    predicted_positives = tf.math.reduce_sum(pred, axis=None)
    precision = hit_positives / (predicted_positives + 1e-9) #tf.keras.backend.epsilon())
    self.n += 1
    self.precision = self.precision * (self.n-1)/self.n + precision / self.n

  def result(self):
    return self.precision
  
  def reset(self):
    self.n = 0
    self.precision = tf.Variable(0.0, dtype=tf.float32)

precision_object = precision(min_seq_len=5)

In [8]:
label = tf.Variable([1, 1, 1, 0])
pred = tf.Variable([0, 0, 1, 1])

recall_object.reset()
recall_object.update(label, pred)
recall_object.update(label, pred)
print(recall_object.result())

precision_object.reset()
precision_object.update(label, pred)
precision_object.update(label, pred)
print(precision_object.result())

tf.Tensor(0.33333334, shape=(), dtype=float32)
tf.Tensor(0.5, shape=(), dtype=float32)


In [ ]:
import tensorflow as tf

a = tf.zeros((10,4,8))
b = tf.ones((10,1,8))

d1 = tf.data.Dataset.from_tensor_slices(a)
d1 = d1.batch(2,drop_remainder=False)      # elements shape (16,4,8)

d2 = tf.data.Dataset.from_tensor_slices(b)
d2 = d2.batch(2,drop_remainder=False)      # elements shape (16,1,8)

d = tf.data.Dataset.zip((d1,d2))
d = d.map(lambda x,y:tf.concat([x,y],axis=-2)) # elements shape (16,4+1,8)

it = iter(d)
x = next(it)

print(x.shape)
print(x)
)

(2, 5, 8)
tf.Tensor(
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]], shape=(2, 5, 8), dtype=float32)


In [1]:

import tensorflow as tf
import numpy as np

In [2]:
profit = tf.Variable([[1,2,3], [4,5,6]], dtype=tf.int32)
print(profit > 4)
print(profit[profit>4])
print(tf.where(profit>4))
print(tf.where(profit>4, profit, profit))

tf.Tensor(
[[False False False]
 [False  True  True]], shape=(2, 3), dtype=bool)
tf.Tensor([5 6], shape=(2,), dtype=int32)
tf.Tensor(
[[1 1]
 [1 2]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [3]:
tf.zeros((0,2))

<tf.Tensor: shape=(0, 2), dtype=float32, numpy=array([], shape=(0, 2), dtype=float32)>

In [8]:
indices = tf.zeros((0,2), dtype=tf.int64)
print([list(id) for id in indices.numpy()])
profits = tf.zeros((0,), dtype=tf.float32)
print(indices)
print(profits)
new_indices = tf.Variable([[1,2], [3,4], [5,6]], dtype=tf.int64)
indices = tf.concat([indices, new_indices], axis=0)
print(indices)
new_profits = tf.Variable([5,6,7], dtype=tf.float32)
profits = tf.concat([profits, new_profits], axis=0)
print(profits)
print(list(profits.numpy()))

[]
tf.Tensor([], shape=(0, 2), dtype=int64)
tf.Tensor([], shape=(0,), dtype=float32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int64)
tf.Tensor([5. 6. 7.], shape=(3,), dtype=float32)
[5.0, 6.0, 7.0]


In [9]:
indices = [list(id) for id in indices.numpy()]
print(indices)
profits = list(profits.numpy())
print(profits)
backtest = [(bookie, gameId, profit) for [bookie, gameId], profit in zip(indices, profits)]
print(backtest)

[[1, 2], [3, 4], [5, 6]]
[5.0, 6.0, 7.0]
[(1, 2, 5.0), (3, 4, 6.0), (5, 6, 7.0)]
